services:
  ai-word-service:
    image: g-zxyw0558-docker.pkg.coding.net/ai/docker/ai_word:0.5
    depends_on:
      - postgres
    ports:
      - 3003:3003
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=vae
      - POSTGRES_PASSWORD=vae94
      - POSTGRES_DB=ai_word
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
